application: webprov-1079
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1

inbound_services:
  - mail

handlers:
  - url: /favicon\.ico
    static_files: images/favicon.ico
    upload: images/favicon\.ico
  - url: /html
    static_dir: html
  - url: /css
    static_dir: css
  - url: /js
    static_dir: js
  - url: /fonts
    static_dir: fonts
  - url: /dict
    static_dir: dict
  - url: /images
    static_dir: images

# Main html page
  - url: /api/.*
    script: api.application
  - url: /.*
    script: main.application



libraries:
  - name: webapp2
    version: latest


skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^/lib/bootstrap/less/.*
  - .*\.less$
  - .*\.scss$
